project:
  type: website

website:
  title: "UCLA PIC 16B Lec 1, Winter 2024"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/PIC16B-ucla
      - icon: twitter
        href: https://twitter.com
format:
  html:
    toc: true
    theme: pulse
    css: styles.css



